### ISSUE TITLE
breakpoints customization

### ISSUE THREAD

**Issue by studiogustodev** [TriPSs/react-jss-grid#1]
-hello!
we need to know if there is any way to customize grid's breakpoints  in order to have a customized resposive grid on our favorite values.
For example, we need to set this breakpoints:
xs: 575,
sm: 576,
md: 768,
lg: 992,
xl: 1200,

Thank you!!

**Comment by TriPSs** [comment]
Hi @GustoIDS,

Yes this is possible when you create your theme, example:
```js
import generateBreakPoints from 'react-jss-grid/utils/breakpoints'

const theme = {
  breakpoints: generateBreakPoints({
    values: {
      xs: 360,
      sm: 600,
      md: 960,
      lg: 1280,
      xl: 1920,
    },
  }),
  ...
}
```

I will also update the readme with this example.

**Comment by studiogustodev** [comment]
Thank you so much!
